{{- if .Values.authorizationPolicy.enabled -}}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "service.fullname" . }}
  labels: {{ include "service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{ include "service.selectorLabels" . | nindent 6 }}
  action: {{ .Values.authorizationPolicy.action | default "ALLOW" }}
  {{ $rulesContent := include "service.authz.rules" . | trim -}}
  {{- if $rulesContent }}
  rules:
    {{ $rulesContent | nindent 4 }}
  {{- else }}
  rules: [ ]
  {{- end }}
{{- end }}
